# Generated by Django 3.2.5 on 2021-09-10 18:31

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20210910_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('8750333d-1a49-4b98-9005-96e91c7e52bc'), primary_key=True, serialize=False),
        ),
    ]
