# Generated by Django 3.2.5 on 2021-09-13 17:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20210913_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(default='150.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('da228735-2649-4001-bdb2-6a65ecc4bf9d'), primary_key=True, serialize=False),
        ),
    ]
