# Generated by Django 3.0.7 on 2021-07-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='used',
            field=models.IntegerField(default=0),
        ),
    ]
