# Generated by Django 3.2.5 on 2021-09-13 17:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20210913_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('227a22fd-2f55-477e-b775-5873983f5149'), primary_key=True, serialize=False),
        ),
    ]
