# Generated by Django 3.0.7 on 2021-08-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_promotion_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=255)),
                ('line_2', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=35)),
                ('county', models.CharField(max_length=35, null=True)),
                ('postcode', models.CharField(max_length=8)),
            ],
        ),
    ]
