# Generated by Django 3.2.5 on 2021-09-14 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20210914_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipping',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('ce629e94-bb67-4486-90a9-26c12cb41ed8'), primary_key=True, serialize=False),
        ),
    ]
