# Generated by Django 3.0.7 on 2021-08-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
