# Generated by Django 3.2.5 on 2021-09-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='Test Name', max_length=127),
            preserve_default=False,
        ),
    ]
