# Generated by Django 3.2.5 on 2021-09-20 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20210916_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('de11eab9-7505-4c1a-8cbc-d38f53be2bcc'), primary_key=True, serialize=False),
        ),
    ]
