# Generated by Django 3.2.5 on 2021-09-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_order_ordercollection_ordercollectionproduct_orderproduct_ordershipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='promotion_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
