# Generated by Django 3.2.5 on 2021-09-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_carouselimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='customer_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='max_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='max_uses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='min_spend',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
