# Generated by Django 3.2.5 on 2021-09-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_auto_20210906_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='customer_limit',
        ),
    ]
