# Generated by Django 3.0.7 on 2021-08-05 21:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0006_promotion_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('code', models.UUIDField(default=uuid.UUID('32b3a313-e13d-461c-89a2-b4aca74cf832'), primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BasketProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.Basket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Product')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.Device'),
        ),
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(through='storefront.BasketProduct', to='staff.Product'),
        ),
    ]
