# Generated by Django 3.0.7 on 2021-08-03 19:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0006_promotion_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('collections', models.ManyToManyField(to='staff.Collection')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.Device')),
                ('products', models.ManyToManyField(to='staff.Product')),
            ],
        ),
    ]
