# Generated by Django 3.2.5 on 2021-08-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
