# Generated by Django 3.2.5 on 2021-08-04 21:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('bacccbba-bcbb-4df9-8ba3-7d3bb279954b'), primary_key=True, serialize=False),
        ),
    ]
