# Generated by Django 3.0.7 on 2021-08-05 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('3cad72be-2826-4c61-ae22-b38e02c5121b'), primary_key=True, serialize=False),
        ),
    ]
