# Generated by Django 3.0.7 on 2021-08-05 21:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_promotion_used'),
        ('storefront', '0002_auto_20210805_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('e21ea5ae-8b75-443e-8f02-926a32c17e3d'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BasketCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.Basket')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Collection')),
            ],
        ),
    ]
