# Generated by Django 3.0.7 on 2021-08-05 17:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_promotion_used'),
        ('storefront', '0002_alter_device_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('5bdaf827-daa0-438d-b05f-9f65de5e302d'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BasketCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.Basket')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Collection')),
            ],
        ),
        migrations.AlterField(
            model_name='basket',
            name='collections',
            field=models.ManyToManyField(through='storefront.BasketCollection', to='staff.Collection'),
        ),
    ]
