# Generated by Django 3.2.5 on 2021-08-04 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_basket_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('106b2d0d-165c-41b5-a5e3-efa859af2f0a'), primary_key=True, serialize=False),
        ),
    ]
