# Generated by Django 3.2.5 on 2021-08-04 20:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_alter_device_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='device_code',
            new_name='device',
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('ab91ea9d-b972-4b2e-be75-735f6f793603'), primary_key=True, serialize=False),
        ),
    ]
