# Generated by Django 3.0.7 on 2021-08-14 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_auto_20210809_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=255)),
                ('line_2', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=35)),
                ('county', models.CharField(max_length=35, null=True)),
                ('postcode', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('1ed9de94-c47d-4ba8-ac25-f3354f6c687e'), primary_key=True, serialize=False),
        ),
    ]
