# Generated by Django 3.2.5 on 2021-08-04 20:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_auto_20210804_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('1e8f08a7-fc8f-4f40-b290-4fdb782b4dad'), primary_key=True, serialize=False),
        ),
    ]
