# Generated by Django 3.0.7 on 2021-08-15 18:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_address'),
        ('storefront', '0007_auto_20210814_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('642e7b2b-7403-4299-b393-54591991b016'), primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
