# Generated by Django 3.0.7 on 2021-08-19 18:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_delivery'),
        ('storefront', '0009_auto_20210815_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Delivery'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('c08c282c-dac2-4579-b95e-6adb06e91ee4'), primary_key=True, serialize=False),
        ),
    ]
