# Generated by Django 3.2.5 on 2021-09-03 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0010_auto_20210819_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('e99e98b0-a856-474e-96ab-d66134cd39b9'), primary_key=True, serialize=False),
        ),
    ]
