# Generated by Django 3.2.5 on 2021-09-03 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0011_alter_device_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('ff87f7d6-0b96-4505-9902-fbd627b38da9'), primary_key=True, serialize=False),
        ),
    ]
