# Generated by Django 3.2.5 on 2021-09-03 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0012_alter_device_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('56b08b5a-33de-4728-9fc1-13f1a615fa95'), primary_key=True, serialize=False),
        ),
    ]
