# Generated by Django 3.2.5 on 2021-09-03 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0013_alter_device_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('1d5a74e4-e631-410a-b08e-9142d1e0a147'), primary_key=True, serialize=False),
        ),
    ]
