# Generated by Django 3.0.7 on 2021-09-05 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0015_alter_device_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('fd44fc68-d61d-4f03-aaf8-28b8ecca844c'), primary_key=True, serialize=False),
        ),
    ]
