# Generated by Django 3.2.5 on 2021-09-06 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0016_auto_20210905_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('201fb11c-179d-4c74-a69a-99ef291a35c7'), primary_key=True, serialize=False),
        ),
    ]
