# Generated by Django 3.2.5 on 2021-09-07 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0017_alter_device_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.UUIDField(default=uuid.UUID('9fbdec8d-ba71-401d-86ad-9f554f87d19a'), primary_key=True, serialize=False),
        ),
    ]
